### ISSUE TITLE
Can't add a single video file in OTVision: Detect

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTVision#107]
Seems like it still want that I choose a folder.

**Comment by frunika** [comment]
#102 should solve it?

**Comment by martinbaerwolff** [comment]
@arminkollascheck I think so, too. With the new tkinter gui and the recent merge from @randy-seng ´s branch I guess this should finally be fixed. I had no problems with this installing OTVision from scratch today. Could you also test it by following the steps from [OTC documentation](https://opentrafficcam.org/OTVision/gettingstarted/installation/#install-python-39) and close this issue if everything works?

**Comment by arminkollascheck** [comment]
Yes, works for me obviously. 

But I would change the name to "Add file" instead of "Add files" or can you load multiple files with that option? I guess not. Can close the issue then.

**Comment by arminkollascheck** [comment]
And btw, OTVision can detect the car in the VICOM Tempus videos :D.

**Comment by martinbaerwolff** [comment]
> Yes, works for me obviously. 
> 
> 
> 
> But I would change the name to "Add file" instead of "Add files" or can you load multiple files with that option? I guess not. Can close the issue then.

Should be possible...did you try?
