### ISSUE TITLE
Idea for deployment of our tools using requirements.txt

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTVision#14]
**On the development machine:**
- Create venv inside the project folder but dont push this to git repository
- Create a "requirements.txt" with pip freeze
- Create a "install.bat" which pip installs all dependencies from the "requierements.txt" to a venv
- Create a "run_project.bat" which starts venv and runs the python script/project and closes the venv after finishing the python script/project (if not possible just add a line in the python script for subprocess)
- Push requirements.txt and both batch files to git repository (together with python script/project)

**On the end user machine:**
- Download a zip archive including python project structure, "requirements.txt" and both batch files
- Double klick "install.bat" (only once after downloading the repository)
- To start the program double klick "run_project.bat"

**Open questions:**
- Do i need admin privileges?
- Is it possible to also activate the venv with the python script and then close it at the end of the script with a subprocess popen?
- Is it also possible to check and if necessary install Python from the batch file?

**Comment by frunika** [comment]
moved to project management
