### ISSUE TITLE
Allow to use custom weights for detection in the OTVision GUI 

### ISSUE THREAD

**Issue by MichHeilig** [OpenTrafficCam/OTVision#158]
Once having trained own model weights, the OTVision user wants to use them within the GUI framework.

**Comment by martinbaerwolff** [comment]
@MichHeilig we tried to implement this - didnt work for [tph-yolo-drone-weights](https://github.com/cv516Buaa/tph-yolov5) but did work for standard yolov5 weigths. Using gui or detect function, just pass a path to a .pt instead of the name of the weights.

**Comment by MichHeilig** [comment]
I know that it is working using the detect function directly. However, I could not find a way to add a custom path in the GUI. Checking the GUI again, I noticed that one can enter a path in the weights dropdown menu. I did not expect that functionality in a dropdown menu.
