### ISSUE TITLE
Error when running 'install_win-py39.bat' file

### ISSUE THREAD

**Issue by mudasser-rafi** [OpenTrafficCam/OTVision#159]
![Error1](https://user-images.githubusercontent.com/102389909/183302023-697619ca-b828-4a5e-b3be-732cdc08c653.png)
Hi 

I am facing the following error when I start to run 'install_win-py39.bat' file.

"Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: GDAL-3.2.3-cp39-cp39-win_amd64.whl is not a supported wheel on this platform."

Don't know what to do.

**Comment by martinbaerwolff** [comment]
Hi @mudasser-rafi, did you already solve the problem?
