### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by lishuoiscas** [OpenTrafficCam/OTVision#172]
Hi frunika,  I find that when recreate execution envirement of OTVision by the command "pip install -r requirements.txt ", there is a conflict dependency.  opencv-python==4.5.3.56 requires numpy>1.21.0, however, it recommand numpy==1.19.5 in "requirements_win-py38.txt".
This problem is similar to "https://github.com/OpenTrafficCam/OTVision/issues/127".  The solution you mentioned doesn't work "Fixed all dependencies to specific versions and prevent pip from installing requirements from cashe at all using --no-cache-dir".

**Comment by frunika** [comment]
Hey @lishuoiscas ,

which OS are you working on?

**Comment by martinbaerwolff** [comment]
@lishuoiscas we hope we adressed this issue with #175. Please reopen if you (or someone else) is running into this error again
