### ISSUE TITLE
sort OTCamera files

### ISSUE THREAD

**Issue by frunika** [OpenTrafficCam/OTVision#29]
### arguments
_path_
_outpath_ (default=None)
_overwrite_ (default=False)

### function
1. get_files(h264) from _path_
1. check if h264 files exist
1. extract Cam, Date, Time
1. move h264 to path/Cam/Date/Time (Time is 2h?)
a. overwrite (default = False)

**Comment by frunika** [comment]
i thinks thats done, isn't it @martinbaerwolff ?

**Comment by martinbaerwolff** [comment]
Only 1.
I think for now we dont need the rest

**Comment by frunika** [comment]
yep
