### ISSUE TITLE
OTCamera importer

### ISSUE THREAD

**Issue by frunika** [OpenTrafficCam/OTVision#30]
### arguments
_dir_
_outputdir_ (=None)
_overwrite_ (=False)

### function
1. check if _dir_ is a dir
1. check filenames?
1. call OTCamera sort files
1. call OTCamera convert files

**Comment by frunika** [comment]
done? @martinbaerwolff

**Comment by martinbaerwolff** [comment]
What I implemented:
Call get_files with path or list of paths, only returns wanted filetypes
convert(overwrite)

Not yet: Sort (maybe call from get_files?)

**Comment by martinbaerwolff** [comment]
No sorting, but I guess not needed any more
