### ISSUE TITLE
Missing parameter "CHUNKSIZE"

### ISSUE THREAD

**Issue by PetersLogistik** [OpenTrafficCam/OTVision#394]
When starting the program, Py generated a key error: 

> Ausnahme: KeyError
'CHUNKSIZE'
  File "..\OTVision\OTVision\view\view_detect.py", line 89, in __init__
    self.scale_chunksize.set(CONFIG["DETECT"]["YOLO"]["CHUNKSIZE"])
                             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "..\OTVision\OTVision\view\view_detect.py", line 39, in __init__
    self.frame_options = FrameDetectOptions(
                         ^^^^^^^^^^^^^^^^^^^
  File "..\OTVision\OTVision\view\view.py", line 61, in set_layout
    self.frame_detect = FrameDetect(master=self, text="Detect")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\OTVision\OTVision\view\view.py", line 42, in __init__
    self.set_layout()
  File "..\OTVision\OTVision\view\view.py", line 85, in main
    app = WindowOTVision()
          ^^^^^^^^^^^^^^^^
  File "..\OTVision\view.py", line 25, in <module>
    main()
KeyError: 'CHUNKSIZE'

To solve the problem, I added the following lines to OTVision > config.py file: 

1. line 88 + `CHUNKSIZE = “CHUNKSIZE”` 
2. line 678 + `CONFIG[DETECT][YOLO][CHUNKSIZE] = 1`.

After I saved it, it works. I hope I did it right. Or did I use/ add a wrong parameter?

**Comment by frunika** [comment]
Hey @PetersLogistik,

your workaround seems correct. Nevertheless, the GUI is outdated and OTVision should be only started as a command line tool. The documentation of OTVision explains the usage: https://opentrafficcam.org/OTVision/gettingstarted/firstuse/

Please note that the documentation of OTAnalytics is completely outdated... :(

Happy detecting

**Comment by PetersLogistik** [comment]
Thank you very much for your quick response. Now I'll try it with the command line tool. :)
